services:
  ducker01:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-driver:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-driver.sh", "sleep", "infinity"]
    depends_on:
      - ducker02
      - ducker03
      - ducker04
      - ducker05
      - ducker06
      - ducker07
      - ducker08
      - ducker09
      - ducker10
      - ducker11
      - ducker12
      - ducker13
      - ducker14
    networks:
      - cluster-net

  ducker02:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-vm:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-vm.sh", "tail", "-f", "/dev/null"]
    networks:
      - cluster-net

  ducker03:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-vm:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-vm.sh", "tail", "-f", "/dev/null"]
    networks:
      - cluster-net

  ducker04:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-vm:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-vm.sh", "tail", "-f", "/dev/null"]
    networks:
      - cluster-net

  ducker05:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-vm:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-vm.sh", "tail", "-f", "/dev/null"]
    networks:
      - cluster-net

  ducker06:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-vm:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-vm.sh", "tail", "-f", "/dev/null"]
    networks:
      - cluster-net

  ducker07:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-vm:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-vm.sh", "tail", "-f", "/dev/null"]
    networks:
      - cluster-net

  ducker08:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-vm:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-vm.sh", "tail", "-f", "/dev/null"]
    networks:
      - cluster-net

  ducker09:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-vm:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-vm.sh", "tail", "-f", "/dev/null"]
    networks:
      - cluster-net

  ducker10:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-vm:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-vm.sh", "tail", "-f", "/dev/null"]
    networks:
      - cluster-net

  ducker11:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-vm:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-vm.sh", "tail", "-f", "/dev/null"]
    networks:
      - cluster-net

  ducker12:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-vm:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-vm.sh", "tail", "-f", "/dev/null"]
    networks:
      - cluster-net

  ducker13:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-vm:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-vm.sh", "tail", "-f", "/dev/null"]
    networks:
      - cluster-net

  ducker14:
    image: us-central1-docker.pkg.dev/molten-verve-216720/aiven-repository/kafka-systest-experiment-vm:latest
    entrypoint: ["/opt/kafka-dev/entrypoint-vm.sh", "tail", "-f", "/dev/null"]
    networks:
      - cluster-net

networks:
  cluster-net:
